# Generated by Django 4.1.5 on 2023-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cropdisease",
            name="disease_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
